# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b9a0b983b61a6e9013a26cfa48c65c59"
name = "Educational Coin"
handle = "educational-coin"
application_url = "https://266f-2403-8940-23-6f-cad4-b86e-9e5f-71a.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "karan-working.myshopify.com"
include_config_on_deploy = true

[access.admin]
direct_api_mode = "offline"
embedded_app_direct_api_access = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://266f-2403-8940-23-6f-cad4-b86e-9e5f-71a.ngrok-free.app/auth/callback",
  "https://266f-2403-8940-23-6f-cad4-b86e-9e5f-71a.ngrok-free.app/auth/shopify/callback",
  "https://266f-2403-8940-23-6f-cad4-b86e-9e5f-71a.ngrok-free.app/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
