# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b9a0b983b61a6e9013a26cfa48c65c59"
name = "Educational Coin"
handle = "educational-coin"
application_url = "https://educational-coin-pdf-upload-app.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "karan-working.myshopify.com"
include_config_on_deploy = true

[access.admin]
direct_api_mode = "offline"
embedded_app_direct_api_access = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,write_orders,write_products"

[auth]
redirect_urls = [
  "https://educational-coin-pdf-upload-app.vercel.app/auth/callback",
  "https://educational-coin-pdf-upload-app.vercel.app/auth/shopify/callback",
  "https://educational-coin-pdf-upload-app.vercel.app/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
